import os
import json
import shutil
import pytest
from unittest.mock import patch, MagicMock

from shared_core.exceptions.custom_exception import CustomException
from pipelines.inference_pipeline.src.components.model_loader import ModelLoader
from pipelines.inference_pipeline.src.entity.artifact_entity import ModelLoaderArtifact


def test_model_loader_initialization_success(mock_pipeline_context):
    """
    Tests that ModelLoader successfully initializes when a valid context is provided.
    """
    loader = ModelLoader(context=mock_pipeline_context)
    assert loader.context is mock_pipeline_context
    assert loader.config is not None
    assert "01_model_loader" in loader.config.model_loader_root_dir


def test_model_loader_initialization_failure(mock_pipeline_context):
    """
    Tests that ModelLoader raises a CustomException if configuration extraction fails.
    """
    with patch(
        "pipelines.inference_pipeline.src.entity.config_entity.ModelLoaderConfig.from_context"
    ) as mock_from_context:
        mock_from_context.side_effect = Exception("Config error")
        with pytest.raises(CustomException) as exc_info:
            ModelLoader(context=mock_pipeline_context)

        assert "Config error" in str(exc_info.value)


def test_model_loader_run_success(mock_pipeline_context, dummy_model_state_path):
    """
    Tests the complete happy path of the Model Loader execution workflow.
    Validates S3 fetching, state pointer parsing, artifact downloading, and metadata generation.
    """

    def s3_download_side_effect(s3_uri, local_path):
        # Simulate downloading the pointer file from S3
        if s3_uri.endswith("model_state.json"):
            shutil.copy(dummy_model_state_path, local_path)
        else:
            # Simulate downloading artifacts by writing dummy data (needed for os.path.getsize)
            with open(local_path, "w", encoding="utf-8") as f:
                f.write("mock_artifact_content")

    mock_pipeline_context.s3_sync.download_file.side_effect = s3_download_side_effect

    loader = ModelLoader(context=mock_pipeline_context)
    artifact = loader.run()

    # Validate output artifact
    assert isinstance(artifact, ModelLoaderArtifact)
    assert artifact.champion_run_id == "champion_run_456"
    assert os.path.exists(artifact.model_file_path)
    assert os.path.exists(artifact.schema_file_path)
    assert os.path.exists(artifact.metadata_file_path)

    # Validate S3 calls (1 for pointer + 4 for artifacts)
    assert mock_pipeline_context.s3_sync.download_file.call_count == 5

    # Validate metadata content
    with open(artifact.metadata_file_path, "r", encoding="utf-8") as f:
        metadata = json.load(f)
        assert metadata["pipeline_stage"] == "Model Loader"
        assert metadata["inference_run_id"] == mock_pipeline_context.run_id
        assert metadata["model_provenance"]["run_id"] == "champion_run_456"
        assert "local_artifact_sizes_bytes" in metadata


def test_model_loader_pointer_download_failure(mock_pipeline_context):
        """
        Tests that failure to download the state pointer from S3 halts execution.
        """
        mock_pipeline_context.s3_sync.download_file.side_effect = Exception("S3 access denied")
        
        loader = ModelLoader(context=mock_pipeline_context)
        
        with pytest.raises(CustomException) as exc_info:
            loader.run()
            
        # FIX: Assert the actual error message generated by the component's exception handler
        assert "Failed to fetch model registry state pointer" in str(exc_info.value)


def test_model_loader_pointer_missing_keys(mock_pipeline_context, temp_workspace):
    """
    Tests that a downloaded state pointer missing required contractual keys raises an error.
    """
    malformed_state_path = temp_workspace / "malformed_model_state.json"
    malformed_data = {
        "run_id": "champion_run_456",
        # Missing other required keys like s3_model_path
    }
    with open(malformed_state_path, "w", encoding="utf-8") as f:
        json.dump(malformed_data, f)

    def s3_download_side_effect(s3_uri, local_path):
        if s3_uri.endswith("model_state.json"):
            shutil.copy(malformed_state_path, local_path)

    mock_pipeline_context.s3_sync.download_file.side_effect = s3_download_side_effect

    loader = ModelLoader(context=mock_pipeline_context)

    with pytest.raises(CustomException) as exc_info:
        loader.run()

    assert "Missing required keys" in str(exc_info.value)
    assert "s3_model_path" in str(exc_info.value)


def test_model_loader_pointer_invalid_json(mock_pipeline_context, temp_workspace):
    """
    Tests that a malformed (non-JSON) state pointer raises a parsing exception.
    """
    invalid_state_path = temp_workspace / "invalid_model_state.json"
    with open(invalid_state_path, "w", encoding="utf-8") as f:
        f.write("This is not a JSON object")

    def s3_download_side_effect(s3_uri, local_path):
        if s3_uri.endswith("model_state.json"):
            shutil.copy(invalid_state_path, local_path)

    mock_pipeline_context.s3_sync.download_file.side_effect = s3_download_side_effect

    loader = ModelLoader(context=mock_pipeline_context)

    with pytest.raises(CustomException) as exc_info:
        loader.run()

    assert "Expecting value" in str(exc_info.value) or "JSON" in str(exc_info.value)


def test_model_loader_artifact_download_failure(
    mock_pipeline_context, dummy_model_state_path
):
    """
    Tests that if the pointer is successfully fetched but a subsequent artifact
    download fails, the process is safely aborted and an exception is raised.
    """

    def s3_download_side_effect(s3_uri, local_path):
        if s3_uri.endswith("model_state.json"):
            shutil.copy(dummy_model_state_path, local_path)
        else:
            raise Exception(f"Failed to download artifact: {s3_uri}")

    mock_pipeline_context.s3_sync.download_file.side_effect = s3_download_side_effect

    loader = ModelLoader(context=mock_pipeline_context)

    with pytest.raises(CustomException) as exc_info:
        loader.run()

    assert "Failed to download" in str(exc_info.value)
    # 1 for pointer + 1 for the first artifact which immediately fails
    assert mock_pipeline_context.s3_sync.download_file.call_count == 2


def test_model_loader_metadata_generation_failure(mock_pipeline_context, dummy_model_state_path):
        """
        Tests that if metadata generation fails, it is wrapped correctly and raises a CustomException.
        """
        def s3_download_side_effect(s3_uri, local_path):
            if s3_uri.endswith("model_state.json"):
                shutil.copy(dummy_model_state_path, local_path)
            else:
                with open(local_path, "w", encoding="utf-8") as f:
                    f.write("mock")

        mock_pipeline_context.s3_sync.download_file.side_effect = s3_download_side_effect
        loader = ModelLoader(context=mock_pipeline_context)
        
        # FIX: Target json.dump specifically so it only fails when writing the metadata file
        with patch("pipelines.inference_pipeline.src.components.model_loader.json.dump", side_effect=PermissionError("Cannot write metadata")):
            with pytest.raises(CustomException) as exc_info:
                loader.run()
                
            assert "Cannot write metadata" in str(exc_info.value)