[pytest]
pythonpath = .
filterwarnings =
    ignore::RuntimeWarning:runpy
    
    # Ignore SHAP matplotlib colormap deprecations
    ignore:The set_bad function will be deprecated:PendingDeprecationWarning
    ignore:The set_over function will be deprecated:PendingDeprecationWarning
    ignore:The set_under function will be deprecated:PendingDeprecationWarning
    # Ignore numpy/pandas swapaxes deprecation triggered by SHAP
    ignore:'DataFrame.swapaxes' is deprecated:FutureWarning
    # Ignore global RNG seed warning triggered by SHAP
    ignore:The NumPy global RNG was seeded by calling:FutureWarning