import os
import sys
import json
import time
from datetime import datetime, timezone
from typing import Dict, Any, List, Tuple

from shared_core.exceptions.custom_exception import CustomException
from shared_core.logging.custom_logging import logging
from pipelines.inference_pipeline.src.core.context import InferencePipelineContext
from pipelines.inference_pipeline.src.entity.config_entity import InferenceValidatorConfig
from pipelines.inference_pipeline.src.entity.artifact_entity import (
    InferenceValidatorArtifact,
    ModelLoaderArtifact,
    FeatureMatrixBuilderArtifact
)


class InferenceValidator:
    """
    Inference Validator Component.

    Responsibilities:
    - Acts as the Gatekeeper for Entity Integrity and Structural Data Contracts.
    - Reads the model schema blueprint generated by the updated Training Pipeline.
    - Reads the actual feature matrix schema generated by the out-of-core DuckDB engine.
    - Validates that all required predictive features (numerical and categorical) exist.
    - Validates that all required system/entity columns (e.g., customer_unique_id) 
      exist to ensure predictions can be accurately mapped to business entities.
    - Generates a validation report and halts the pipeline gracefully if the data contract is violated.
    """

    def __init__(self, context: InferencePipelineContext) -> None:
        """
        Initializes the Inference Validator component.

        Args:
            context (InferencePipelineContext): The centralized execution context.
        """
        try:
            self.context = context
            self.config = InferenceValidatorConfig.from_context(context)
            logging.info("Inference Pipeline: Inference Validator component initialized.")
        except Exception as e:
            logging.exception("Failed to initialize Inference Validator component.")
            raise CustomException(e, sys) from e

    def run(
        self, 
        model_loader_artifact: ModelLoaderArtifact, 
        feature_matrix_artifact: FeatureMatrixBuilderArtifact
    ) -> InferenceValidatorArtifact:
        """
        Executes the structural data contract verification workflow.

        Args:
            model_loader_artifact (ModelLoaderArtifact): Artifact containing the model schema path.
            feature_matrix_artifact (FeatureMatrixBuilderArtifact): Artifact containing the builder schema path.

        Returns:
            InferenceValidatorArtifact: Artifact containing the validation status and report path.
        """
        try:
            logging.info("Starting Structural Data Contract Validation Sequence.")
            start_time = time.time()

            # 1. Load Schemas
            model_schema, builder_schema = self._load_schemas(
                model_schema_path=model_loader_artifact.schema_file_path,
                builder_schema_path=feature_matrix_artifact.schema_file_path
            )

            # 2. Validate Data Contract
            is_valid, validation_errors = self._validate_data_contract(
                model_schema=model_schema,
                builder_schema=builder_schema
            )

            # 3. Generate Validation Report
            self._generate_validation_report(
                is_valid=is_valid,
                validation_errors=validation_errors
            )

            # 4. Generate Operational Metadata
            execution_time = round(time.time() - start_time, 2)
            self._generate_metadata(
                is_valid=is_valid,
                execution_time=execution_time
            )

            # 5. Package Artifact
            artifact = InferenceValidatorArtifact(
                is_valid=is_valid,
                report_file_path=self.config.report_file_path
            )

            if not is_valid:
                logging.error("Data contract validation failed. Refer to validation report for details.")
            else:
                logging.info("Data contract validation passed successfully.")

            return artifact

        except Exception as e:
            logging.exception("Critical Failure inside Inference Validator execution routine.")
            raise CustomException(e, sys) from e

    def _load_schemas(self, model_schema_path: str, builder_schema_path: str) -> Tuple[Dict[str, Any], List[Dict[str, Any]]]:
        """
        Loads the model's expected schema blueprint and the actual feature matrix schema.
        """
        try:
            logging.debug("Loading expected model schema blueprint from: %s", model_schema_path)
            with open(model_schema_path, "r", encoding="utf-8") as f:
                model_schema = json.load(f)

            logging.debug("Loading actual feature matrix schema from: %s", builder_schema_path)
            with open(builder_schema_path, "r", encoding="utf-8") as f:
                builder_schema = json.load(f)

            return model_schema, builder_schema

        except Exception as e:
            logging.exception("Failed to load schema JSON files.")
            raise CustomException(e, sys) from e

    def _validate_data_contract(
        self, 
        model_schema: Dict[str, Any], 
        builder_schema: List[Dict[str, Any]]
    ) -> Tuple[bool, List[str]]:
        """
        Validates entity integrity and predictive feature completeness.
        
        The updated Training Pipeline outputs a nested schema blueprint:
        {"features": {"numerical": [...], "categorical": {...}}}
        
        The DuckDB Builder outputs a flat list of dictionaries:
        [{"name": "...", "physical_type": "..."}, ...]
        """
        try:
            is_valid = True
            errors: List[str] = []

            # Extract actual column names from the DuckDB output
            actual_columns = {col["name"] for col in builder_schema}

            # 1. Extract expected predictive features from the Model Schema
            features_dict = model_schema.get("features", {})
            numerical_features = features_dict.get("numerical", [])
            categorical_features = list(features_dict.get("categorical", {}).keys())
            
            expected_model_features = set(numerical_features + categorical_features)

            # 2. Extract expected system entity columns from Configuration
            business_cfg = self.context.config.get_business_logic_config()
            system_columns = set(business_cfg.get("system_columns_to_drop", []))

            # 3. Perform Set Difference Validations
            missing_model_features = expected_model_features - actual_columns
            if missing_model_features:
                is_valid = False
                error_msg = f"Missing predictive features required by the model: {sorted(list(missing_model_features))}"
                errors.append(error_msg)
                logging.error(error_msg)

            missing_system_columns = system_columns - actual_columns
            if missing_system_columns:
                is_valid = False
                error_msg = f"Missing system/entity columns required for business mapping: {sorted(list(missing_system_columns))}"
                errors.append(error_msg)
                logging.error(error_msg)

            # Note: We do not validate data types rigorously here because the new CategoricalSchemaEnforcer 
            # in the Scikit-Learn pipeline handles type casting and NaN injection automatically during inference.
            # We strictly enforce Entity Integrity (column existence).

            return is_valid, errors

        except Exception as e:
            logging.exception("Error occurred during data contract validation logic.")
            raise CustomException(e, sys) from e

    def _generate_validation_report(self, is_valid: bool, validation_errors: List[str]) -> None:
        """
        Writes the structured validation findings to the artifact directory.
        """
        try:
            report = {
                "validation_status": "PASSED" if is_valid else "FAILED",
                "timestamp_utc": datetime.now(timezone.utc).isoformat(),
                "errors": validation_errors
            }

            with open(self.config.report_file_path, "w", encoding="utf-8") as f:
                json.dump(report, f, indent=4)
                
            logging.debug("Validation report saved to: %s", self.config.report_file_path)

        except Exception as e:
            logging.exception("Failed to write validation report.")
            raise CustomException(e, sys) from e

    def _generate_metadata(self, is_valid: bool, execution_time: float) -> None:
        """
        Generates comprehensive operational metadata for observability.
        """
        try:
            metadata: Dict[str, Any] = {
                "pipeline_stage": "Inference Validator",
                "inference_run_id": self.context.run_id,
                "execution_time_seconds": execution_time,
                "validation_outcome": {
                    "is_valid": is_valid,
                    "report_file": self.config.report_file_path
                },
                "timestamp_utc": datetime.now(timezone.utc).isoformat()
            }

            with open(self.config.metadata_file_path, "w", encoding="utf-8") as f:
                json.dump(metadata, f, indent=4)
                
            logging.debug("Inference Validator metadata saved to: %s", self.config.metadata_file_path)

        except Exception as e:
            logging.exception("Failed to generate Inference Validator metadata.")
            raise CustomException(e, sys) from e