import sys
import time
from datetime import datetime, timezone
from typing import Dict, Any

import pandas as pd
import joblib

from shared_core import constants
from pipelines.inference_pipeline.src.entity.config_entity import ReportGenerationConfig
from pipelines.inference_pipeline.src.entity.artifact_entity import (
    InferenceModelLoaderArtifact,
    InferenceInputFeatureMatrixBuilderArtifact,
    InferenceReportGeneratorArtifact,
)
from shared_core.exceptions.custom_exception import CustomException
from shared_core.logging.custom_logging import logging
from shared_core.utils.main_utils import write_json_file


class ReportGeneration:
    """
    Report Generator (Inference Publisher) Component.

    Responsibilities:
    - Load the unified feature matrix and the active Champion model pipeline.
    - Generate continuous predictions (churn probabilities).
    - Calculate a robust business metric (Revenue at Risk) using existing features.
    - Output `telemetry_log.parquet` containing exact point-in-time features and 
      predictions for downstream drift detection and monitoring.
    - Output `customer_churn_report.csv` formatted for business consumption, filtered
      by probability and strictly ordered by Revenue at Risk.
    - Output `metadata.json` capturing the pipeline's operational execution state.
    """

    def __init__(
        self,
        config: ReportGenerationConfig,
        loader_artifact: InferenceModelLoaderArtifact,
        builder_artifact: InferenceInputFeatureMatrixBuilderArtifact,
    ) -> None:
        """
        Initializes the Report Generator component.
        """
        try:
            self.config = config
            self.loader_artifact = loader_artifact
            self.builder_artifact = builder_artifact

            logging.info("Inference Pipeline: Report Generator (Publisher) component initialized.")

        except Exception as e:
            logging.exception("Failed to initialize Report Generator component.")
            raise CustomException(e, sys) from e

    # ==========================================================
    # PUBLIC ENTRYPOINT
    # ==========================================================
    def run(self) -> InferenceReportGeneratorArtifact:
        """
        Executes the prediction, metric calculation, and artifact generation workflow.

        Returns:
            InferenceReportGeneratorArtifact: Contains paths to the generated artifacts.
        """
        try:
            logging.info("Starting Inference Report Generation and Telemetry Logging.")
            start_time = time.time()

            # 1. Load Data
            df = self._load_feature_matrix()
            total_input_rows = len(df)

            if total_input_rows == 0:
                logging.warning("Feature matrix is empty. Proceeding to generate empty artifacts.")
            
            # 2. Load Model Pipeline
            model_pipeline = self._load_model()

            # 3. Generate Predictions & Calculate Business Metric (Revenue at Risk)
            df = self._process_predictions_and_metrics(df, model_pipeline)

            # 4. Generate Telemetry Log (Engineering Artifact)
            self._generate_telemetry_log(df)

            # 5. Generate Customer Churn Report (Business Artifact)
            total_churners_flagged, total_rar = self._generate_business_report(df)

            # 6. Generate Observability Metadata
            execution_time = round(time.time() - start_time, 2)
            self._generate_metadata(
                total_input_rows=total_input_rows,
                total_churners_flagged=total_churners_flagged,
                total_revenue_at_risk=total_rar,
                execution_time=execution_time,
            )

            # 7. Package and Return Artifact
            artifact = InferenceReportGeneratorArtifact(
                csv_report_path=self.config.csv_report_path,
                telemetry_log_path=self.config.telemetry_log_path,
                metadata_file_path=self.config.metadata_file_path,
            )

            logging.info("Report Generator execution completed successfully: %s", artifact)
            return artifact

        except Exception as e:
            logging.exception("Critical Failure inside Report Generator execution routine.")
            raise CustomException(e, sys) from e

    # ==========================================================
    # DATA & MODEL LOADING
    # ==========================================================
    def _load_feature_matrix(self) -> pd.DataFrame:
        """Loads the Parquet feature matrix generated by the Builder component."""
        try:
            matrix_path = self.builder_artifact.feature_matrix_file_path
            logging.debug("Loading feature matrix from: %s", matrix_path)
            return pd.read_parquet(matrix_path)
        except Exception as e:
            logging.exception("Failed to load feature matrix.")
            raise CustomException(e, sys) from e

    def _load_model(self) -> Any:
        """Loads the serialized Scikit-Learn deployment pipeline."""
        try:
            model_path = self.loader_artifact.model_file_path
            logging.debug("Loading model pipeline from: %s", model_path)
            return joblib.load(model_path)
        except Exception as e:
            logging.exception("Failed to load model pipeline.")
            raise CustomException(e, sys) from e

    # ==========================================================
    # PREDICTION & METRIC CALCULATION
    # ==========================================================
    def _process_predictions_and_metrics(self, df: pd.DataFrame, model_pipeline: Any) -> pd.DataFrame:
        """
        Isolates predictive features, runs inference, and calculates Revenue at Risk.
        Returns the mutated DataFrame containing predictions.
        """
        try:
            if df.empty:
                df["predicted_probability"] = pd.Series(dtype=float)
                df["revenue_at_risk"] = pd.Series(dtype=float)
                return df

            logging.info("Isolating features and generating predictions.")
            
            # Identify system entity columns to drop before passing to the model
            cols_to_drop = [c for c in constants.SYSTEM_COLUMNS_TO_DROP if c in df.columns]
            X_inference = df.drop(columns=cols_to_drop)

            # Generate Calibrated Probabilities
            y_proba = model_pipeline.predict_proba(X_inference)[:, 1]
            df["predicted_probability"] = y_proba

            # Calculate Revenue at Risk (Proxy for Business Value)
            if "monetary_total" in df.columns:
                df["revenue_at_risk"] = df["predicted_probability"] * df["monetary_total"]
            else:
                logging.warning("Feature 'monetary_total' missing. Setting revenue_at_risk to 0.0.")
                df["revenue_at_risk"] = 0.0

            return df

        except Exception as e:
            logging.exception("Failed to generate predictions and business metrics.")
            raise CustomException(e, sys) from e

    # ==========================================================
    # ARTIFACT GENERATION
    # ==========================================================
    def _generate_telemetry_log(self, df: pd.DataFrame) -> None:
        """
        Generates the point-in-time telemetry log for downstream monitoring and drift detection.
        Includes all input features, entity IDs, prediction outputs, and execution metadata.
        """
        try:
            logging.info("Generating Parquet telemetry log for MLOps monitoring.")
            telemetry_df = df.copy()

            # Append Operational Metadata for Tracing
            telemetry_df["inference_run_id"] = self.config.run_id
            telemetry_df["timestamp_utc"] = datetime.now(timezone.utc)
            telemetry_df["champion_model_id"] = self.loader_artifact.champion_run_id

            telemetry_df.to_parquet(self.config.telemetry_log_path, index=False, compression='snappy')
            logging.debug("Telemetry log saved to: %s", self.config.telemetry_log_path)

        except Exception as e:
            logging.exception("Failed to generate telemetry log.")
            raise CustomException(e, sys) from e

    def _generate_business_report(self, df: pd.DataFrame) -> tuple[int, float]:
        """
        Generates the business-facing CSV report. 
        Filters out low-risk customers, sorts by Revenue at Risk, and drops ML-specific features.
        
        Returns:
            tuple[int, float]: (total_churners_flagged, total_revenue_at_risk)
        """
        try:
            logging.info("Generating customer churn CSV report for business consumers.")
            
            if df.empty:
                empty_df = pd.DataFrame(columns=["customer_unique_id", "predicted_probability", "monetary_total", "revenue_at_risk"])
                empty_df.to_csv(self.config.csv_report_path, index=False)
                return 0, 0.0

            # 1. Filter by Threshold
            threshold = self.config.probability_threshold
            business_df = df[df["predicted_probability"] >= threshold].copy()

            total_churners = len(business_df)
            total_rar = float(business_df["revenue_at_risk"].sum()) if total_churners > 0 else 0.0

            # 2. Sort by Expected Financial Impact
            business_df.sort_values(by="revenue_at_risk", ascending=False, inplace=True)

            # 3. Restrict Schema to Business-Friendly Columns
            target_columns = ["customer_unique_id", "predicted_probability", "monetary_total", "revenue_at_risk"]
            actual_columns = [c for c in target_columns if c in business_df.columns]

            business_df[actual_columns].to_csv(self.config.csv_report_path, index=False)
            logging.debug("Customer churn report saved to: %s", self.config.csv_report_path)

            return total_churners, total_rar

        except Exception as e:
            logging.exception("Failed to generate business report.")
            raise CustomException(e, sys) from e

    def _generate_metadata(
        self, 
        total_input_rows: int, 
        total_churners_flagged: int, 
        total_revenue_at_risk: float, 
        execution_time: float
    ) -> None:
        """
        Generates standard telemetry metadata ensuring complete operational observability.
        """
        try:
            logging.info("Generating Report Generator operational metadata.")

            metadata: Dict[str, Any] = {
                "pipeline_stage": "Inference Publisher (Report Generator)",
                "inference_run_id": self.config.run_id,
                "execution_time_seconds": execution_time,
                "model_context": {
                    "champion_run_id": self.loader_artifact.champion_run_id,
                    "classification_threshold": self.config.probability_threshold,
                },
                "volumetrics": {
                    "total_customers_scored": total_input_rows,
                    "total_churners_flagged": total_churners_flagged,
                    "total_revenue_at_risk": round(total_revenue_at_risk, 2),
                },
                "destinations": {
                    "business_report_path": self.config.csv_report_path,
                    "telemetry_log_path": self.config.telemetry_log_path,
                },
                "timestamp": datetime.now(timezone.utc).isoformat(),
            }

            write_json_file(file_path=self.config.metadata_file_path, content=metadata)
            logging.debug("Metadata securely saved to: %s", self.config.metadata_file_path)

        except Exception as e:
            logging.exception("Failed to generate operational metadata.")
            raise CustomException(e, sys) from e