import sys
import time

from shared_core.exceptions.custom_exception import CustomException
from shared_core.logging.custom_logging import logging

from pipelines.inference_pipeline.src.core.context import InferencePipelineContext
from pipelines.inference_pipeline.src.components.model_loader import ModelLoader
from pipelines.inference_pipeline.src.components.feature_matrix_builder import FeatureMatrixBuilder
from pipelines.inference_pipeline.src.components.inference_validator import InferenceValidator
from pipelines.inference_pipeline.src.components.report_generator import ReportGenerator
from pipelines.inference_pipeline.src.components.report_publisher import ReportPublisher
from pipelines.inference_pipeline.src.entity.artifact_entity import ReportPublisherArtifact


class InferencePipeline:
    """
    Orchestration entry point for the Inference Pipeline.

    Responsibilities:
    - Manages the lifecycle of the entire batch inference workflow.
    - Initializes the centralized `InferencePipelineContext`, ensuring secure
      management of out-of-core DuckDB engines and AWS S3 connections.
    - Coordinates the sequential execution of all pipeline components.
    - Halts execution gracefully if data contracts or validation checks fail.
    - Propagates generated artifacts through the pipeline stages to ensure
      strict state determinism and lineage tracking.
    """

    @classmethod
    def run(cls, run_id: str) -> ReportPublisherArtifact:
        """
        Executes the end-to-end inference workflow for a given run ID.

        Args:
            run_id (str): A unique identifier for the current batch execution
                          (e.g., generated by an external orchestrator like Airflow).

        Returns:
            ReportPublisherArtifact: The final artifact containing cloud URIs to the
                                     published reports and master telemetry ledger.

        Raises:
            CustomException: If any unrecoverable error occurs during execution.
            RuntimeError: If structural data contract validation fails, forcing a fast failure.
        """
        logging.info("==========================================================")
        logging.info(" INFERENCE PIPELINE EXECUTION INITIATED")
        logging.info(" RUN ID: %s", run_id)
        logging.info("==========================================================")

        start_time = time.time()

        try:
            # Instantiate the execution context. This securely injects the
            # DuckDB engine, config parser, and S3 client to all components,
            # guaranteeing that connections are closed upon exit or failure.
            with InferencePipelineContext(run_id=run_id) as context:
                
                # ---------------------------------------------------------
                # Stage 1: Model Loading
                # ---------------------------------------------------------
                logging.info(">>> STAGE 1: Starting Model Loader...")
                model_loader = ModelLoader(context)
                model_loader_artifact = model_loader.run()
                
                # ---------------------------------------------------------
                # Stage 2: Feature Matrix Construction
                # ---------------------------------------------------------
                logging.info(">>> STAGE 2: Starting Feature Matrix Builder...")
                feature_builder = FeatureMatrixBuilder(context)
                feature_matrix_artifact = feature_builder.run()
                
                # ---------------------------------------------------------
                # Stage 3: Data Contract Validation (Gatekeeper)
                # ---------------------------------------------------------
                logging.info(">>> STAGE 3: Starting Inference Validator...")
                validator = InferenceValidator(context)
                validator_artifact = validator.run(
                    model_loader_artifact=model_loader_artifact,
                    feature_matrix_artifact=feature_matrix_artifact
                )
                
                # Fail Fast: Prevent scoring if data contracts are breached
                if not validator_artifact.is_valid:
                    error_msg = (
                        "Pipeline halted: Structural Data Contract Validation failed. "
                        f"See validation report at {validator_artifact.report_file_path} for details."
                    )
                    logging.error(error_msg)
                    raise RuntimeError(error_msg)

                # ---------------------------------------------------------
                # Stage 4: Batch Scoring & Report Generation
                # ---------------------------------------------------------
                logging.info(">>> STAGE 4: Starting Report Generator...")
                report_generator = ReportGenerator(context)
                report_generator_artifact = report_generator.run(
                    model_loader_artifact=model_loader_artifact,
                    feature_matrix_artifact=feature_matrix_artifact
                )
                
                # ---------------------------------------------------------
                # Stage 5: Artifact Publication & Ledger Consolidation
                # ---------------------------------------------------------
                logging.info(">>> STAGE 5: Starting Report Publisher...")
                publisher = ReportPublisher(context)
                publisher_artifact = publisher.run(
                    model_loader_artifact=model_loader_artifact,
                    feature_matrix_artifact=feature_matrix_artifact,
                    validator_artifact=validator_artifact,
                    report_generator_artifact=report_generator_artifact
                )

            # Context manager __exit__ executes here, safely closing DuckDB connections
            
            execution_time = round(time.time() - start_time, 2)
            logging.info("==========================================================")
            logging.info(" INFERENCE PIPELINE EXECUTION COMPLETED SUCCESSFULLY")
            logging.info(" TOTAL EXECUTION TIME: %s seconds", execution_time)
            logging.info("==========================================================")
            
            return publisher_artifact

        except Exception as e:
            logging.exception("Inference Pipeline execution failed critically for run_id: %s", run_id)
            raise CustomException(e, sys) from e