"""
Entity package for the Inference Pipeline.

This package defines the strictly typed data structures used to pass state, 
configurations, and execution metadata between pipeline components. 
It enforces clear data contracts by distinguishing between Configuration Entities 
(runtime parameters, paths, and business logic) and Artifact Entities 
(immutable outputs and metadata generated by components).
"""

from .artifact_entity import (
    FeatureMatrixBuilderArtifact,
    InferenceValidatorArtifact,
    ModelLoaderArtifact,
    ReportGeneratorArtifact,
    ReportPublisherArtifact,
)
from .config_entity import (
    FeatureMatrixBuilderConfig,
    InferenceValidatorConfig,
    ModelLoaderConfig,
    ReportGeneratorConfig,
    ReportPublisherConfig,
)

__all__ = [
    "FeatureMatrixBuilderArtifact",
    "InferenceValidatorArtifact",
    "ModelLoaderArtifact",
    "ReportGeneratorArtifact",
    "ReportPublisherArtifact",
    "FeatureMatrixBuilderConfig",
    "InferenceValidatorConfig",
    "ModelLoaderConfig",
    "ReportGeneratorConfig",
    "ReportPublisherConfig",
]